name: Lint and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm run lint
      - run: npm test
  coverage:
    needs: test-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm run coverage
      - uses: actions/upload-artifact@v2
        with:
          name: Coverage Results
          path: coverage/lcov-report
  deployGhPages:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: Coverage Results
          path: coverage-results
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: coverage-results
  deployApp:
    needs: deployGhPages
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secret.SSH_HOST}}
          key: ${{secret.SSH_KEY}}
          username: ${{secret.SSH_USERNAME}}
          script: |
            touch itworks
